package memory

import "github.com/paperstacks.io/paperstacks/internal/paper/domain"

func seedData() []domain.Paper {
	return []domain.Paper{
		{
			DOI:   "10.1109/isese.2005.1541817",
			Title: "Exploratory testing: a multiple case study",
			Authors: []domain.Author{
				{NameFirst: "J.", NameLast: "Itkonen"},
				{NameFirst: "K.", NameLast: "Rautiainen"},
			},
			Keywords: []string{
				"Computer aided software engineering",
				"Design engineering",
				"Software testing",
				"Application software",
				"System testing",
				"Performance evaluation",
				"Software quality",
				"Product development",
				"Exploratory testing",
				"Test design",
				"Testing coverage",
				"Regression test",
				"Testing techniques",
				"Test plan",
				"Usability problems",
				"Software development",
			},
			Type: "proceedings-article",
			Metadata: domain.Metadata{
				Publisher:   "IEEE",
				PublishedIn: "2005 International Symposium on Empirical Software Engineering, 2005.",
				Pages:       "82-91",
			},
			PublicationYear: "2005",
		},
		{
			DOI:   "10.1016/j.infsof.2023.107299",
			Title: "Code review guidelines for GUI-based testing artifacts",
			Authors: []domain.Author{
				{NameFirst: "Andreas", NameLast: "Bauer", Affiliation: "Blekinge Institute of Technology"},
				{NameFirst: "Riccardo", NameLast: "Coppola", Affiliation: "Politecnico di Torino"},
				{NameFirst: "Emil", NameLast: "Alégroth", Affiliation: "Blekinge Institute of Technology"},
				{NameFirst: "Tony", NameLast: "Gorschek", Affiliation: "Blekinge Institute of Technology"},
			},
			Keywords: []string{
				"GUI testing",
				"GUI-based testing",
				"Software testing",
				"Code review",
				"Modern code review",
				"Guidelines",
				"Practices",
			},
			Type: "journal-article",
			Metadata: domain.Metadata{
				Publisher:   "Elsevier BV",
				PublishedIn: "Information and Software Technology",
				Pages:       "107299",
			},
			PublicationYear: "2023",
		},
		{
			DOI:   "10.1109/icstw58534.2023.00015",
			Title: "We Tried and Failed: An Experience Report on a Collaborative Workflow for GUI-based Testing",
			Authors: []domain.Author{
				{NameFirst: "Andreas", NameLast: "Bauer", Affiliation: "Blekinge Institute of Technology"},
				{NameFirst: "Emil", NameLast: "Alégroth", Affiliation: "Blekinge Institute of Technology"},
			},
			Keywords: []string{
				"Collaboration",
				"Software development",
				"Graphical user interface",
				"Level of abstraction",
				"Testing tools",
				"Code review",
				"Unforeseen challenges",
				"Source code",
				"Historical changes",
				"Common tool",
				"Visual model",
				"Time zones",
				"Incremental chan, year stringge",
				"Changes in integrity",
				"Global organization",
				"Unified modeling language",
				"Design patterns",
				"Concurrent changes",
				"Code changes",
				"Way of communication",
				"JavaScript object notation",
				"Version control system",
				"Linux kernel",
				"Synchronous communication",
				"Asynchronous communication",
				"Agile development",
				"Open standards",
				"Testing coverage",
				"Development of workflows",
				"Ways of working",
				"Model-based testing",
				"Automated testing",
				"GUI testing",
				"Collaborative testing",
				"Collaborative workflow",
			},
			Type: "proceedings-article",
			Metadata: domain.Metadata{
				Publisher:   "IEEE",
				PublishedIn: "2023 IEEE International Conference on Software Testing, Verification and Validation Workshops (ICSTW)",
				Pages:       "1-9",
			},
			PublicationYear: "2023",
		},
		{
			DOI:   "10.1007/s10664-024-10522-z",
			Title: "Augmented testing to support manual GUI-based regression testing: An empirical study",
			Authors: []domain.Author{
				{NameFirst: "Andreas", NameLast: "Bauer", Affiliation: "Blekinge Institute of Technology"},
				{NameFirst: "Julian", NameLast: "Frattini", Affiliation: "Blekinge Institute of Technology"},
				{NameFirst: "Emil", NameLast: "Alégroth", Affiliation: "Blekinge Institute of Technology"},
			},
			Keywords: []string{
				"GUI-based testing",
				"GUI testing",
				"Augmented testing",
				"Manual testing",
				"Bayesian data analysis",
			},
			Type: "journal-article",
			PublicationYear: "2024",
		},
	}
}
