services:
  db:
    image: postgres:18-alpine
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d:ro
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_super_password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    secrets:
      - db_super_password
      - db_app_rw_password
      - db_app_ro_password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080

secrets:
  db_super_password:
    file: ../secrets/db_super_password.txt
  db_app_rw_password:
    file: ../secrets/db_app_rw_password.txt
  db_app_ro_password:
    file: ../secrets/db_app_ro_password.txt
